name: furious_app
description: Gestionnaire d'historique de ma voiture.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"  # Dart 3.x (Flutter 3.13+)
  flutter: ">=3.13.0"    # Exige Flutter 3.13 ou supérieur

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8       # Mise à jour mineure
  http: ^1.5.0                  # Correction de sécurité
  fl_chart: ^1.1.1              # OK
  flutter_settings_screens: ^0.3.4  # Remplacez par `settings_ui: ^2.0.2` si possible
  shared_preferences: ^2.5.3   # Mise à jour majeure (vérifiez Android/iOS)
  syncfusion_flutter_pdf: ^31.1.23  # OK (licence requise)
  syncfusion_flutter_charts: ^31.1.23 # OK (licence requise)
  path_provider: ^2.1.5        # Compatible avec Flutter 3.13+
  open_file: ^3.5.10           # Mise à jour recommandée
  permission_handler: ^12.0.1  # OK (vérifiez les permissions)
  provider: ^6.1.5             # Mise à jour mineure
  intl: ^0.20.2                # OK
  uuid: ^4.0.0
  flutter_secure_storage: ^9.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0        # OK
  test: ^1.24.0                # Ajout pour les tests unitaires

flutter:
  uses-material-design: true
  assets:
    - assets/images/images.jpg
    - assets/images/waiting.png
